# Generated by Django 3.1.7 on 2021-04-07 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
